### ISSUE TITLE
Install via project installer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/flexible_layout#2]
Would it be possible to break out the Layout code into a separate (layout) project that was required by this one? That would allow (ideally) someone to install via the project installer without having to figure out how to upload a layout folder manually.

**Comment by docwilmot** [comment]
Makes very good sense; ideally if either one is installed without the other, it prompts via message. Can you PR?

**Comment by laryn** [comment]
I've done a quick test of adding a dependency in the layout template but it doesn't seem to work. Maybe modules/layouts can't be interdependent in that way? Are you suggesting a simple message at the top of the page or a status report error?

**Comment by oadaeh** [comment]
I haven't actually done this, so I'm not sure how well it would work or what details would be required, but I think you should be able to create a custom/contrib module that is effectively only the layout configuration and then depend on that module. There might need to be an extra step of importing the configuration, but maybe not or maybe a function could be executed on install to do it.

**Comment by docwilmot** [comment]
@oadaeh this is an actual layout template package (with the info file, the tpl file etc) rather than a layout config, so that wouldnt work. Dependencies would have been a good idea too.

I was thinking though just a `backdrop_set_message('the template/module respectively is missing')`.

@laryn I think splitting this into a layout template is a better idea, because then it would actiually be listed as a project in the layouts list on b/cms.org. Right now not many people would find it as a module.

**Comment by docwilmot** [comment]
@laryn did you start working on this?

**Comment by laryn** [comment]
No. Just early testing on the dependency idea.

**Comment by docwilmot** [comment]
Done this, but in a new branch 2.0.0 instead because not sure what implications for existing sites would be.
Thanks.
