### ISSUE TITLE
Undefined indexes when editing blocks on flexible layout

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/flexible_layout#3]
I'm seeing this at the top of the layout block edit page:

> Notice: Undefined index: header in include() (line 28 of /path/core/modules/layout/templates/layout.tpl.php).
> Notice: Undefined index: top in include() (line 34 of /path/core/modules/layout/templates/layout.tpl.php).
> Notice: Undefined index: content in include() (line 64 of /path/core/modules/layout/templates/layout.tpl.php).
> Notice: Undefined index: footer in include() (line 68 of /path/core/modules/layout/templates/layout.tpl.php).

Maybe we should set up the flexible layout with a few basic regions already defined?

**Comment by docwilmot** [comment]
Funny thing, the module actually wasnt using the provided template at all, because of a missing dash in the template name, so it was falling back to the core default `layout-single-column` legacy layout template, and so was complaining because that template was expecting those regions. 

Fixed. Thanks.

**Comment by docwilmot** [comment]
Just to be clear this is fixed but only in the new 2.0.0 branch as I'm not sure the implications of switching templates; CSS might be messed up on existing sites, I assume. Better safe.
